-- ============================================================================
-- Customer Lifetime Value (CLV) Analysis
-- ============================================================================
-- Purpose: Calculate comprehensive customer lifetime value metrics to identify
--          the most valuable customers and understand customer behavior patterns.
--
-- Business Questions:
--   - Who are our most valuable customers by total revenue?
--   - What is the average order value per customer?
--   - How long do customers typically stay active?
--   - What is the daily revenue contribution per customer?
--
-- SQL Techniques:
--   - Common Table Expressions (CTEs) for query organization
--   - Window functions (RANK) for customer ranking
--   - Date calculations (DATEDIFF) for lifespan analysis
--   - Aggregate functions (COUNT, SUM, AVG) for metrics
--   - NULLIF for safe division operations
--
-- ============================================================================

USE SCHEMA ECOMMERCE_DW.PRODUCTION;

-- Step 1: Calculate base customer metrics
WITH customer_metrics AS (
  SELECT
    c.customer_key,
    c.customer_id,
    co.country_name,

    -- Order metrics
    COUNT(DISTINCT f.invoice_no) AS total_orders,

    -- Revenue metrics
    SUM(f.total_amount) AS lifetime_revenue,
    AVG(f.total_amount) AS avg_order_value,

    -- Time-based metrics
    MIN(d.date) AS first_purchase_date,
    MAX(d.date) AS last_purchase_date,
    DATEDIFF(DAY, MIN(d.date), MAX(d.date)) AS customer_lifespan_days

  FROM ECOMMERCE_DW.PRODUCTION.fact_sales f
  JOIN ECOMMERCE_DW.PRODUCTION.dim_customer c ON f.customer_key = c.customer_key
  JOIN ECOMMERCE_DW.PRODUCTION.dim_country co ON f.country_key = co.country_key
  JOIN ECOMMERCE_DW.PRODUCTION.dim_date d ON f.date_key = d.date_key
  GROUP BY c.customer_key, c.customer_id, co.country_name
)

-- Step 2: Calculate derived metrics and rank customers
SELECT
  customer_id,
  country_name,
  total_orders,
  ROUND(lifetime_revenue, 2) AS lifetime_revenue,
  ROUND(avg_order_value, 2) AS avg_order_value,
  first_purchase_date,
  last_purchase_date,
  customer_lifespan_days,

  -- Calculate revenue per day (handle single-purchase customers)
  CASE
    WHEN customer_lifespan_days > 0 THEN
      ROUND(lifetime_revenue / NULLIF(customer_lifespan_days, 0), 2)
    ELSE NULL
  END AS revenue_per_day,

  -- Rank customers by lifetime revenue
  RANK() OVER (ORDER BY lifetime_revenue DESC) AS revenue_rank

FROM customer_metrics
ORDER BY lifetime_revenue DESC
LIMIT 100;

-- ============================================================================
-- Expected Output Columns:
--   - customer_id: Unique customer identifier
--   - country_name: Customer's country
--   - total_orders: Number of distinct orders placed
--   - lifetime_revenue: Total revenue generated by customer
--   - avg_order_value: Average spend per order
--   - first_purchase_date: Date of first purchase
--   - last_purchase_date: Date of most recent purchase
--   - customer_lifespan_days: Days between first and last purchase
--   - revenue_per_day: Average daily revenue contribution
--   - revenue_rank: Customer ranking by lifetime value
--
-- Business Insights:
--   - Top 100 customers by lifetime value
--   - Customer purchase frequency patterns
--   - Customer retention indicators (lifespan)
--   - Revenue concentration analysis
-- ============================================================================
